services:
  db:
    image: postgres:15
    container_name: digital_vision_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: digital_vision_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${DOCKER_PORT}:${PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      environment:
      NODE_ENV: production 
      DOCKER_ENV: "true"  # 🟢 Added this to detect Docker environment
    command: [ "sh", "-c", "yarn prisma migrate deploy && yarn start:prod" ]

volumes:
  postgres_data:
